### ISSUE TITLE
Is is possible to hide the 'setObject' control from events?

### ISSUE THREAD

**Issue by rstoneIDBS** [break-stuff/wc-storybook-helpers#42] opened 2024-02-09 09:13 UTC
Not a huge issue, but when events are listed in the docs they include a useless 'setObject' control. I had a quick go at removing this with no success and suspect that this is just a Storybook *thing* but wanted to log it in case it turns out to be possible.

**Comment by break-stuff** [comment] 2024-02-09 11:30
Yeah, that's a good call-out. We should be able to disable those.

**Comment by break-stuff** [comment] 2024-02-23 19:03
@rstoneIDBS, this should be resolved in release 1.4.0. Let me know if you run into any issues.

**Comment by rstoneIDBS** [comment] 2024-02-26 09:28
1.4.0 fixes this issue, thanks @break-stuff - however see https://github.com/break-stuff/wc-storybook-helpers/issues/51 for a possible negative side effect of this (or one of the other changes) ?

**Comment by certainlyakey** [comment] 2024-02-27 20:28
I too have noticed that starting from 1.4.0 events get converted into attributes: 

```
<my-button data-color-scheme="light" onlmclick="function() {
            return fn2.apply(this, arguments);
          }" appearance="primary">
    Default content
</my-button>
```

This happens both in the generated example code in story docs and in the rendered HTML.

Perhaps caused by #44?

**Comment by break-stuff** [comment] 2024-02-28 01:55
Fixed in release 1.5.1 (#56). Let me know if you run into any issues.

**Comment by rstoneIDBS** [comment] 2024-02-28 08:56
Thanks @break-stuff, this fixes it. It might be worth looking at the lit^2.6.1 peer dependency as this caused me some install issues as it didn't like lit^3.1.2

**Comment by break-stuff** [comment] 2024-02-28 12:05
Release 1.5.2 should resolve that issue. Closing this as I believe the original issue has been resolved.

**Closed by break-stuff** 2024-02-28 12:05 UTC
